[package]
name = "flaky-test-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
crossterm = "0.27.0"
rayon = "1.10.0"

[profile.release]
opt-level = 3
strip = "debuginfo"
lto = "thin"
